#!/usr/bin/env bash
# APKAM enrollment for NoPorts on Junos OS Evolved: cuts new, scope-limited
# keys for this router ON the router — the full atKeys file for the device
# Atsign never leaves the administrator's custody.
#
# Run INSIDE the running noports container, from the Junos shell
# (`start shell`, root):
#
#   docker exec -it noports onboard-noports.sh <passcode>
#
# where <passcode> is an OTP or SPP generated by an administrator with an
# already-authorized key for the device Atsign, e.g. on their machine:
#
#   at_activate otp -a @mydevice          # one-time passcode, or
#   at_activate spp -a @mydevice -s <passcode> -e 1d
#
# While this script waits, the administrator approves the request:
#
#   at_activate approve -a @mydevice --arx noports --drx <device-name>
#
# On approval the APKAM keys are written to the persistent keys mount
# (/var/extensions/noports/keys on the routing engine) and the entrypoint's
# wait loop starts sshnpd automatically within ~30 seconds.
set -euo pipefail

NOPORTS_KEYS_DIR="${NOPORTS_KEYS_DIR:-/atsign/keys}"
ROOT_SERVER="${ROOT_SERVER:-root.atsign.org}"

if [ -z "${DEVICE_ATSIGN:-}" ] || [ -z "${DEVICE_NAME:-}" ]; then
    echo "onboard: DEVICE_ATSIGN / DEVICE_NAME not set." >&2
    echo "Set them in /var/extensions/noports/noports.env on the routing" >&2
    echo "engine, restart the container, and re-run this script." >&2
    exit 1
fi

case "$DEVICE_ATSIGN" in
    @*) ;;
    *) DEVICE_ATSIGN="@${DEVICE_ATSIGN}" ;;
esac

KEY_FILE="${NOPORTS_KEYS_DIR}/${DEVICE_ATSIGN}_key.atKeys"

PASSCODE="${1:-}"
if [ -z "$PASSCODE" ]; then
    read -r -s -p "Enrollment passcode (OTP/SPP) for ${DEVICE_ATSIGN}: " PASSCODE
    echo
fi

if [ -f "$KEY_FILE" ]; then
    echo "onboard: $KEY_FILE already exists; delete it first to re-enroll" >&2
    exit 1
fi

mkdir -p "$NOPORTS_KEYS_DIR"

echo "Requesting APKAM enrollment for ${DEVICE_ATSIGN} (device ${DEVICE_NAME})..."
echo "Approve it from an authorized client, e.g.:"
echo "  at_activate approve -a ${DEVICE_ATSIGN} --arx noports --drx ${DEVICE_NAME}"

# Enrollment traffic follows the same egress path as the daemon, honoring
# ROOT_SERVER (proxy:host:443 form included).
/usr/local/bin/at_activate enroll \
    --atsign "$DEVICE_ATSIGN" \
    --root-server "$ROOT_SERVER" \
    --passcode "$PASSCODE" \
    --app noports \
    --device "$DEVICE_NAME" \
    --namespaces "sshnp:rw,sshrvd:rw" \
    --keys "$KEY_FILE"

chmod 0600 "$KEY_FILE"
echo
echo "Enrollment complete; APKAM keys written to $KEY_FILE"
echo "(persisted on the routing engine at /var/extensions/noports/keys)"
echo "The entrypoint wait loop will start sshnpd within ~30s:"
echo "  docker logs -f noports"
